<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property \DTS\eBaySDK\Trading\Types\AmountType $AmountPaid
 * @property \DTS\eBaySDK\Trading\Types\AmountType $AdjustmentAmount
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConvertedAdjustmentAmount
 * @property \DTS\eBaySDK\Trading\Types\UserType $Buyer
 * @property \DTS\eBaySDK\Trading\Types\ShippingDetailsType $ShippingDetails
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConvertedAmountPaid
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ConvertedTransactionPrice
 * @property \DateTime $CreatedDate
 * @property \DTS\eBaySDK\Trading\Enums\DepositTypeCodeType $DepositType
 * @property \DTS\eBaySDK\Trading\Types\ItemType $Item
 * @property integer $QuantityPurchased
 * @property \DTS\eBaySDK\Trading\Types\TransactionStatusType $Status
 * @property string $TransactionID
 * @property \DTS\eBaySDK\Trading\Types\AmountType $TransactionPrice
 * @property boolean $BestOfferSale
 * @property integer $VATPercent
 * @property \DTS\eBaySDK\Trading\Types\ExternalTransactionType[] $ExternalTransaction
 * @property \DTS\eBaySDK\Trading\Types\SellingManagerProductDetailsType $SellingManagerProductDetails
 * @property \DTS\eBaySDK\Trading\Types\ShippingServiceOptionsType $ShippingServiceSelected
 * @property \DTS\eBaySDK\Trading\Enums\PaidStatusCodeType $BuyerPaidStatus
 * @property \DTS\eBaySDK\Trading\Enums\PaidStatusCodeType $SellerPaidStatus
 * @property \DateTime $PaidTime
 * @property \DateTime $ShippedTime
 * @property \DTS\eBaySDK\Trading\Types\AmountType $TotalPrice
 * @property \DTS\eBaySDK\Trading\Types\FeedbackInfoType $FeedbackLeft
 * @property \DTS\eBaySDK\Trading\Types\FeedbackInfoType $FeedbackReceived
 * @property \DTS\eBaySDK\Trading\Types\OrderType $ContainingOrder
 * @property \DTS\eBaySDK\Trading\Types\AmountType $FinalValueFee
 * @property \DTS\eBaySDK\Trading\Enums\SiteCodeType $TransactionSiteID
 * @property \DTS\eBaySDK\Trading\Enums\TransactionPlatformCodeType $Platform
 * @property string $PayPalEmailAddress
 * @property string $PaisaPayID
 * @property \DTS\eBaySDK\Trading\Types\AmountType $BuyerGuaranteePrice
 * @property \DTS\eBaySDK\Trading\Types\VariationType $Variation
 * @property string $BuyerCheckoutMessage
 * @property \DTS\eBaySDK\Trading\Types\AmountType $TotalTransactionPrice
 * @property \DTS\eBaySDK\Trading\Types\TaxesType $Taxes
 * @property boolean $BundlePurchase
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ActualShippingCost
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ActualHandlingCost
 * @property string $OrderLineItemID
 * @property string $eBayPaymentID
 * @property \DTS\eBaySDK\Trading\Types\PaymentHoldDetailType $PaymentHoldDetails
 * @property \DTS\eBaySDK\Trading\Types\SellerDiscountsType $SellerDiscounts
 * @property string $CodiceFiscale
 * @property boolean $IsMultiLegShipping
 * @property \DTS\eBaySDK\Trading\Types\MultiLegShippingDetailsType $MultiLegShippingDetails
 * @property \DateTime $InvoiceSentTime
 * @property \DTS\eBaySDK\Trading\Types\UnpaidItemType $UnpaidItem
 * @property boolean $IntangibleItem
 * @property \DTS\eBaySDK\Trading\Types\PaymentsInformationType $MonetaryDetails
 * @property \DTS\eBaySDK\Trading\Types\PickupDetailsType $PickupDetails
 * @property \DTS\eBaySDK\Trading\Types\PickupMethodSelectedType $PickupMethodSelected
 * @property \DTS\eBaySDK\Trading\Types\AmountType $ShippingConvenienceCharge
 * @property string $LogisticsPlanType
 * @property \DTS\eBaySDK\Trading\Types\BuyerPackageEnclosuresType $BuyerPackageEnclosures
 * @property string $InventoryReservationID
 * @property string $ExtendedOrderID
 * @property boolean $eBayPlusTransaction
 * @property \DTS\eBaySDK\Trading\Types\GiftSummaryType $GiftSummary
 * @property \DTS\eBaySDK\Trading\Types\DigitalDeliverySelectedType $DigitalDeliverySelected
 * @property boolean $Gift
 * @property boolean $GuaranteedShipping
 * @property boolean $GuaranteedDelivery
 */
class ServiceCostType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Amount' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Amount'
        ],
        'ConvertedFromAmount' => [
            'type' => 'DTS\eBaySDK\Trading\Types\AmountType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Amount'
        ],
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        [$parentValues, $childValues] = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
