<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class AuthenticityVerificationStatusType
{
    const C_PENDING = 'PENDING';
    const C_PASSED = 'PASSED';
    const C_PASSED_WITH_EXCEPTION = 'PASSED_WITH_EXCEPTION';
    const C_PASSED_WITH_PARTIAL_FAILURE = 'PASSED_WITH_PARTIAL_FAILURE';
    const C_FAILED = 'FAILED';
}
